---
- name: Base | Install base packages
  apt:
    name:
      - curl
      - wget
      - gcc
      - python3
      - git
      - vim
    state: present

- name: Base | Add kali linux key
  apt_key:
    url: https://archive.kali.org/archive-key.asc
    state: present

- name: Base | Add kali linux repository
  apt_repository:
    repo: "deb-src http://http.kali.org/kali kali-rolling main non-free contrib"
    state: present
