---
- name: Infosec | Install tools for penetration testing
  hosts: all

  roles:
    - role: base
      tags: base

    - role: docker
      tags: docker

    - role: exploitation
      tags: exploitation

    - role: information-gathering
      tags: information-gathering

    - role: reverse-engineering
      tags: reverse-engineering

    - role: sniffer
      tags: sniffer
